project:
  title: Neil's Site
  type: website
  output-dir: docs

website:
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: blog.qmd
        text: Writing
      - href: websites.qmd
        text: Cool Websites
    right:
      - href: assets/cv.pdf
        text: My CV

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    link-external-newwindow: true
    citations-hover: true
    fontsize: 1em
    page-layout: full
    
cookie-consent:
   type: express
   style: simple
