project:
  type: website
  output-dir: docs

website:
  title: "Neil Natarajan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: cv.pdf
        text: Curriculum Vitae

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



