project:
  type: website
  output-dir: docs

website:
  title: "Neil Natarajan"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
  # uncomment this when there are other pages to put here
  #     - href: research.qmd
  #       text: Research

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    link-external-newwindow: true
    citations-hover: true
    fontsize: 1em
    page-layout: full
    
cookie-consent:
   type: express
   style: simple
