project:
  type: website
  output-dir: docs

website:
  title: "Neil Natarajan"
  search: false
  # uncomment this when there are other pages to put here
  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - href: research.qmd
  #       text: Research

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true
    citations-hover: true
    mainfont: helvetica
    fontsize: 1em
    page-layout: full
    
cookie-consent:
   type: express
   style: simple
