---
title: "2023-07-28"
author: "Neil Natarajan"
date: "2023-07-28"
categories: [Fiction]
image: "image.svg"
about:
  template: solana
  image-shape: rounded
  image-width: 10em
---

_image taken from [en.wikipedia.org/wiki/Shades_of_yellow](https://en.wikipedia.org/wiki/Shades_of_yellow)_

Only the insane go outside these days. There are few things worse than the toxic air of the moon, but admittedly, this comes close.

I haven't left this room in a week. Carter comes in and out, and he tells me that some day soon he'll be able to smuggle me out to the belt, but until he does, I'm the world's most wanted fugitive. It's funny – in the movies, being a fugitive is always so exciting: exciting chases, thrilling games of cat-and-mouse. Hell, even when they're hiding, it's interesting. At this point, I'm not even scared I'll be caught. I'm just bored.

My new world is a run-down storage closet on the sixty-fifth floor of the excavationary. The gravity's alright, the air's a bit stuffy, and it's actually a decent size. It's got those old flourescent lights – you know, the ones that flicker? I've no idea why anyone ever built anything with those, and can't imagine how it ended up on the moon, but I guess those lights are here to stay. The worst part of my room is the puke-yellow wallpaper. It's nauseating and captivating and I spend all my time staring at it because I have nothing to do.

You know, I almost miss the fear. At least that was something. Come to think of it, shouldn't I be hysterical? I haven't seen the sun in who knows how long, and my only human interaction is with Carter. Carter could bore a brick. This wall is a better conversationalist.

So I just stare at my wall.

You know, it's actually not so bad. I noticed a few days ago that the wallpaper has subtle swirls in it. It's yellow-on-yellow, but there's a slightly raised pattern of clockwise swirls.

I noticed today that there's actually two shades of yellow in the wallpaper. There's a counterclockwise motion in colour grades that forms a nice counterpoint to the swirls.

You know what? It's actually not so bad. Maybe I'll stare at the wallpaper a bit longer.